version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: magnatesting_db
    volumes:
      - db_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - '3306:3306'

  php-apache:
    image: php:8.1-apache
    volumes:
      - ./frontend:/var/www/html
      - ./api:/var/www/html/api
    ports:
      - '8080:80'
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - '8081:80'
    depends_on:
      - db

volumes:
  db_data:
